# ML-06 — Signal Audit: Do the Flags Hold?

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mathu2112/FlyRank-ML-Internship-Repo/blob/main/work/notebooks/w04_signal_audit.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Distributions

*Look before deciding: distributions of your key fields. Note the heavy tails.*

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 2. Signal test #1 / #2 / #3 (verdict each)

*Three safe signals, each with a mini-test and a verdict: CONFIRMED / OPPOSITE / MIXED / FALSE.*

---
Signal Check 1 - CTR distribution

What I am testing: CTR relative to search position.

Why I chose this signal: CTR versus position is linked to FlyRank's CTR-fix logic. Content appearing in similar search-position ranges can have different click-through rates, so I first check whether CTR shows a clear relationship with position before using it in a rule.

What I will measure: I calculate CTR as clicks divided by impressions. I then group content into position buckets and calculate the number of observations (n) and average CTR for each bucket.

Signal Check 2 - CTR vs Search Position

Verdict: CONFIRMED. The results show a clear relationship between search position and CTR. Mean CTR decreases consistently as the average search position becomes worse, falling from 0.016720 for content in positions 1–3 to 0.000404 for content in positions 51+. The bucket counts (n) are substantial across all groups, so the pattern is supported by a large number of observations. This confirms that CTR should be interpreted together with search position rather than being used alone.

Signal Check 3 - Volume/Impressions

Verdict: MIXED
Signal: Impression volume

I grouped content into impression-volume buckets and calculated the number of observations (n) and mean CTR for each bucket. Mean CTR was similar across the groups and did not show a consistent increase or decrease as impression volume increased.

Verdict: MIXED. Impression volume alone does not show a clear relationship with CTR. However, impressions can still be useful when prioritising actions because a low-CTR item with many impressions may represent a larger potential opportunity than an item with only a few impressions.



In [ ]:
# This cell is for CODE (numbers, a query, a check).
#Importing data from huggingface
!pip install -q datasets duckdb pyarrow pandas huggingface_hub

from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

#For Accessing dataset
from datasets import load_dataset

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    token=HF_TOKEN
)
print(dataset)

# Check some report dates
print(dataset["train"]["report_date"][:10])
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB            

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B            

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})
[datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27), datetime.date(2025, 1, 27)]


In [ ]:
# Look at the main performance signals
print(dataset["train"].select_columns([
    "report_date",
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position"
]).to_pandas().head())

  report_date  gsc_impressions  gsc_clicks  gsc_avg_position
0  2025-01-27             30.0         0.0          3.833333
1  2025-01-27              5.0         0.0         71.600000
2  2025-01-27              1.0         0.0         34.000000
3  2025-01-27              6.0         0.0         23.333333
4  2025-01-27              5.0         0.0         17.800000


In [ ]:
# ============================================================
# THREE SIGNAL TESTS — LIGHTWEIGHT VERSION
# ============================================================

import pandas as pd


# Take 1 million rows WITHOUT shuffling

train = dataset["train"]

sample_data = train.select(range(1000000))

print(sample_data)


# Convert the sample to pandas
df = sample_data.select_columns([
    "report_date",
    "content_hash_id",
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position"
]).to_pandas()


# ============================================================
# SIGNAL TEST 1 — CTR
# ============================================================

# Calculate CTR = clicks / impressions
# Rows with zero impressions will have missing CTR

df["ctr"] = df["gsc_clicks"] / df["gsc_impressions"]

df.loc[
    df["gsc_impressions"].isna() |
    (df["gsc_impressions"] == 0),
    "ctr"
] = None

print("\nSIGNAL TEST 1 — CTR SUMMARY")
display(df["ctr"].describe())


# ============================================================
# SIGNAL TEST 2 — SEARCH POSITION
# ============================================================

# Create position buckets

position_bins = [
    -float("inf"),
    3,
    10,
    20,
    50,
    float("inf")
]

position_labels = [
    "1-3",
    "4-10",
    "11-20",
    "21-50",
    "51+"
]

df["position_bucket"] = pd.cut(
    df["gsc_avg_position"],
    bins=position_bins,
    labels=position_labels
)

# Create bucket table with n and mean CTR

position_summary = (
    df
    .dropna(subset=["ctr", "position_bucket"])
    .groupby(
        "position_bucket",
        observed=True
    )
    .agg(
        n=("ctr", "count"),
        mean_ctr=("ctr", "mean")
    )
    .reset_index()
)

print("\nSIGNAL TEST 2 — CTR VS SEARCH POSITION")
display(position_summary)


# ============================================================
# SIGNAL TEST 3 — VOLUME / IMPRESSIONS
# ============================================================

# Create volume buckets

volume_bins = [
    -1,
    0,
    10,
    100,
    1000,
    float("inf")
]

volume_labels = [
    "0",
    "1-10",
    "11-100",
    "101-1000",
    "1000+"
]

df["volume_bucket"] = pd.cut(
    df["gsc_impressions"],
    bins=volume_bins,
    labels=volume_labels
)

# Create bucket table with n and mean CTR

volume_summary = (
    df
    .dropna(subset=["volume_bucket"])
    .groupby(
        "volume_bucket",
        observed=True
    )
    .agg(
        n=("ctr", "count"),
        mean_ctr=("ctr", "mean")
    )
    .reset_index()
)

print("\nSIGNAL TEST 3 — VOLUME / IMPRESSIONS")
display(volume_summary)

Dataset({
    features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
    num_rows: 1000000
})

SIGNAL TEST 1 — CTR SUMMARY


,ctr
count,1000000.000000
mean,0.005064
std,0.034812
min,0.000000
25%,0.000000
50%,0.000000
75%,0.000000
max,1.000000



SIGNAL TEST 2 — CTR VS SEARCH POSITION


,position_bucket,n,mean_ctr
0,1-3,29107,0.016720
1,4-10,272373,0.009176
2,11-20,178878,0.006575
3,21-50,308522,0.002646
4,51+,211117,0.000404



SIGNAL TEST 3 — VOLUME / IMPRESSIONS


,volume_bucket,n,mean_ctr
0,1-10,494881,0.005094
1,11-100,438238,0.004948
2,101-1000,65113,0.005620
3,1000+,1768,0.004865


## 3. The flag-linked test

*Pick a signal one of FlyRank's real flags relies on. Does the data support the rule's assumption?*

---
Baseline rule

Based on the signal checks, I created a rule to identify content that may have a CTR improvement opportunity. The rule focuses on content with a reasonably good search position because the flag-linked test confirmed that CTR depends strongly on position. I also require a minimum number of impressions so that the item has enough search visibility to represent a meaningful opportunity.

Content is flagged when it has an average search position of 20 or better, at least 100 impressions, and a CTR below 0.5%. Flagged content receives an action score based on its impression volume and CTR gap. The reason code is LOW_CTR_GOOD_POSITION, and the action label is INVESTIGATE_CTR.

This is a hand-written baseline rule rather than a machine-learning model. The purpose is to create a transparent baseline that can later be compared with the Week 5 model.

---

Top-10 review

I reviewed the ten highest-scoring rows produced by the baseline rule. All ten rows have an average search position within the top 20, more than 2,000 impressions, and zero clicks, resulting in a CTR of 0. These rows are ranked highly because they combine strong search visibility with a very low observed CTR, suggesting a potential CTR improvement opportunity.

A possible limitation is that daily performance can be noisy. A low or zero CTR may be normal for the specific queries shown, and average position can hide variation across different search queries. Therefore, the action should be interpreted as a recommendation to investigate rather than proof that the content definitely has a problem.

| Rank | Action            | Why it's there                                                  | What would make it wrong                                                                      |
| ---- | ----------------- | --------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| 1    | `INVESTIGATE_CTR` | Position 5.40, 3,350 impressions, and 0 clicks gave a CTR of 0. | Zero CTR may be normal for the queries or the daily result may be unusual.                    |
| 2    | `INVESTIGATE_CTR` | Position 5.98, 3,330 impressions, and 0 clicks gave a CTR of 0. | The low CTR may be caused by query mix rather than a fixable content problem.                 |
| 3    | `INVESTIGATE_CTR` | Position 8.60, 3,089 impressions, and 0 clicks gave a CTR of 0. | Average position may hide different positions across individual queries.                      |
| 4    | `INVESTIGATE_CTR` | Position 8.69, 3,049 impressions, and 0 clicks gave a CTR of 0. | The observed zero CTR could be temporary or normal for the searches involved.                 |
| 5    | `INVESTIGATE_CTR` | Position 8.49, 2,864 impressions, and 0 clicks gave a CTR of 0. | Search-result features or query intent may reduce clicks even with a good position.           |
| 6    | `INVESTIGATE_CTR` | Position 5.68, 2,848 impressions, and 0 clicks gave a CTR of 0. | The result could be affected by short-term daily variation.                                   |
| 7    | `INVESTIGATE_CTR` | Position 8.01, 2,835 impressions, and 0 clicks gave a CTR of 0. | The content may rank for queries where users do not need to click through.                    |
| 8    | `INVESTIGATE_CTR` | Position 5.93, 2,793 impressions, and 0 clicks gave a CTR of 0. | Position alone does not guarantee clicks, and the search snippet may not be the actual issue. |
| 9    | `INVESTIGATE_CTR` | Position 6.79, 2,234 impressions, and 0 clicks gave a CTR of 0. | The query mix or SERP features may explain the low CTR.                                       |
| 10   | `INVESTIGATE_CTR` | Position 5.94, 2,190 impressions, and 0 clicks gave a CTR of 0. | The daily observation may not represent the content's typical long-term performance.          |

---

Flag-linked test: CTR vs Search Position


I selected CTR relative to search position as my flag-linked test because search position is a signal behind FlyRank's CTR-fix logic. I calculated CTR as GSC clicks divided by GSC impressions and grouped the observations into search-position buckets. For each bucket, I calculated the number of observations (n) and mean CTR.

Verdict: CONFIRMED. Mean CTR consistently decreased as search position became worse, from 0.016720 in positions 1–3 to 0.000404 in positions 51+. This confirms that search position is an important context for interpreting CTR


In [ ]:
# ============================================================
# BASELINE ACTION RULE
# ============================================================

import numpy as np
import pandas as pd

# Create a copy for scoring
baseline_df = df.copy()

# ------------------------------------------------------------
# RULE CONDITIONS
# ------------------------------------------------------------

good_position = (
    baseline_df["gsc_avg_position"] > 0
) & (
    baseline_df["gsc_avg_position"] <= 20
)

enough_impressions = (
    baseline_df["gsc_impressions"] >= 100
)

low_ctr = (
    baseline_df["ctr"] < 0.005
)

# Content must satisfy all three conditions
baseline_df["flagged"] = (
    good_position
    & enough_impressions
    & low_ctr
)

# ------------------------------------------------------------
# CREATE ACTION SCORE
# Higher impressions + lower CTR = higher priority
# ------------------------------------------------------------

baseline_df["action_score"] = 0.0

baseline_df.loc[
    baseline_df["flagged"],
    "action_score"
] = (
    np.log1p(
        baseline_df.loc[
            baseline_df["flagged"],
            "gsc_impressions"
        ]
    )
    *
    (
        0.005
        - baseline_df.loc[
            baseline_df["flagged"],
            "ctr"
        ]
    )
)

# ------------------------------------------------------------
# REASON CODE
# ------------------------------------------------------------

baseline_df["reason_code"] = np.where(
    baseline_df["flagged"],
    "LOW_CTR_GOOD_POSITION",
    "NOT_FLAGGED"
)

# ------------------------------------------------------------
# ACTION LABEL
# ------------------------------------------------------------

baseline_df["action_label"] = np.where(
    baseline_df["flagged"],
    "INVESTIGATE_CTR",
    "NO_ACTION"
)

# ------------------------------------------------------------
# CREATE RANKED QUEUE
# ------------------------------------------------------------

ranked_queue = (
    baseline_df[
        baseline_df["flagged"]
    ]
    .sort_values(
        "action_score",
        ascending=False
    )
    [
        [
            "report_date",
            "content_hash_id",
            "gsc_impressions",
            "gsc_clicks",
            "gsc_avg_position",
            "ctr",
            "action_score",
            "reason_code",
            "action_label"
        ]
    ]
    .reset_index(drop=True)
)

# Add rank
ranked_queue.index = ranked_queue.index + 1
ranked_queue.index.name = "rank"

print("Number of items flagged:", len(ranked_queue))

display(ranked_queue.head(10))

Number of items flagged: 31715


,report_date,content_hash_id,gsc_impressions,gsc_clicks,gsc_avg_position,ctr,action_score,reason_code,action_label
rank,,,,,,,,,
1,2025-05-07,content_641bed4d0ac6954f,3350,0,5.398806,0.0,0.040585,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
2,2025-05-09,content_641bed4d0ac6954f,3330,0,5.982282,0.0,0.040555,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
3,2025-05-05,content_cf651123f1085418,3089,0,8.603755,0.0,0.040180,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
4,2025-05-01,content_cf651123f1085418,3049,0,8.688094,0.0,0.040114,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
5,2025-04-10,content_cf651123f1085418,2864,0,8.489176,0.0,0.039802,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
6,2025-05-11,content_641bed4d0ac6954f,2848,0,5.681882,0.0,0.039774,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
7,2025-05-31,content_cf651123f1085418,2835,0,8.012346,0.0,0.039751,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
8,2025-05-10,content_641bed4d0ac6954f,2793,0,5.927676,0.0,0.039676,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR
9,2025-05-17,content_811c0e6db6e2cb7b,2234,0,6.792748,0.0,0.038560,LOW_CTR_GOOD_POSITION,INVESTIGATE_CTR


## 4. What this means in practice

*Two or three sentences: what a content team should take from this.*

---
The results show that CTR depends strongly on search position. Content appearing in lower search positions naturally receives a lower CTR, so a low CTR alone should not automatically be treated as a problem. In practice, a more useful action rule should compare CTR together with search position. Content with a relatively good position but unusually low CTR may be a better candidate for investigation or CTR improvement, especially when it also has enough impressions to make the potential impact worthwhile.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.